// Generated by https://quicktype.io

export interface Provincia {
    IDMunicipio: string;
    IDPovincia: string;
    IDCCAA: string;
    Municipio: string;
    Provincia: string;
    CCAA: string;
}

